# Generated by Django 5.0 on 2023-12-26 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('CourseID', models.AutoField(primary_key=True, serialize=False)),
                ('CourseName', models.CharField(max_length=255)),
                ('Department', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('ProfessorID', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=255)),
                ('LastName', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=254)),
                ('Department', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('StudentID', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=255)),
                ('LastName', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('AssignmentID', models.AutoField(primary_key=True, serialize=False)),
                ('AssignmentName', models.CharField(max_length=255)),
                ('Deadline', models.DateField()),
                ('CourseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='ProfessorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.professor'),
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('GradeID', models.AutoField(primary_key=True, serialize=False)),
                ('Score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('AssignmentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.assignment')),
                ('StudentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.student')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.course')),
                ('StudentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.student')),
            ],
        ),
    ]
