# Generated by Django 5.0 on 2023-12-27 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_assignment_created_at_assignment_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='ProfileImage',
            field=models.ImageField(blank=True, null=True, upload_to='artist_images/'),
        ),
    ]
