# Generated by Django 5.0 on 2023-12-27 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0003_professor_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='ProfileImage',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
