# Generated by Django 5.0 on 2023-12-27 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0004_alter_professor_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='ProfileImage',
            field=models.ImageField(blank=True, null=True, upload_to='professor_images/'),
        ),
    ]
