# Generated by Django 5.0 on 2023-12-29 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0005_alter_professor_profileimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='artist',
            fields=[
                ('created_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artistID', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=255)),
                ('LastName', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=254)),
                ('Department', models.CharField(max_length=255)),
                ('ProfileImage', models.ImageField(blank=True, null=True, upload_to='artist_images/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='title',
            fields=[
                ('created_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titleID', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=255)),
                ('LastName', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='grade',
            name='AssignmentID',
        ),
        migrations.RemoveField(
            model_name='course',
            name='ProfessorID',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='CourseID',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='StudentID',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='StudentID',
        ),
        migrations.CreateModel(
            name='duration',
            fields=[
                ('created_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('durationID', models.AutoField(primary_key=True, serialize=False)),
                ('durationName', models.CharField(max_length=255)),
                ('Department', models.CharField(max_length=255)),
                ('artistID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.artist')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='date_added',
            fields=[
                ('created_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_addedID', models.AutoField(primary_key=True, serialize=False)),
                ('date_addedName', models.CharField(max_length=255)),
                ('Deadline', models.DateField()),
                ('durationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.duration')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='albums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('durationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.duration')),
                ('titleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.title')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
        migrations.DeleteModel(
            name='Professor',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
