# Generated by Django 5.0 on 2023-12-29 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0006_artist_title_remove_grade_assignmentid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='Department',
        ),
        migrations.RemoveField(
            model_name='duration',
            name='Department',
        ),
    ]
