# Generated by Django 5.0 on 2023-12-29 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0008_rename_deadline_date_added_date_added_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='date_added',
            old_name='date_added',
            new_name='Deadline',
        ),
        migrations.RenameField(
            model_name='duration',
            old_name='songsName',
            new_name='durationName',
        ),
    ]
