# Generated by Django 5.0 on 2023-12-30 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0010_rename_durationid_albums_artist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albums',
            name='song_name',
        ),
        migrations.AddField(
            model_name='albums',
            name='song',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='record.title'),
        ),
    ]
